// Données NBA embarquées : 30 franchises et leurs effectifs (saison 2024-25).
// rating ∈ [60, 99] pilote la cote au mercato et la simulation des matchs.

export type Position = 'MJ' | 'AR' | 'AI' | 'AF' | 'PI';
// MJ = Meneur (PG), AR = Arrière (SG), AI = Ailier (SF), AF = Ailier fort (PF), PI = Pivot (C)

export const POSITIONS: Position[] = ['MJ', 'AR', 'AI', 'AF', 'PI'];

export const POSITION_LABELS: Record<Position, string> = {
  MJ: 'Meneur',
  AR: 'Arrière',
  AI: 'Ailier',
  AF: 'Ailier fort',
  PI: 'Pivot',
};

export interface SeedTeam {
  abbr: string;
  name: string;
  city: string;
  conference: 'Est' | 'Ouest';
}

export interface SeedPlayer {
  name: string;
  team: string; // abbr
  pos: Position;
  rating: number;
}

export const TEAMS: SeedTeam[] = [
  { abbr: 'ATL', name: 'Hawks', city: 'Atlanta', conference: 'Est' },
  { abbr: 'BOS', name: 'Celtics', city: 'Boston', conference: 'Est' },
  { abbr: 'BKN', name: 'Nets', city: 'Brooklyn', conference: 'Est' },
  { abbr: 'CHA', name: 'Hornets', city: 'Charlotte', conference: 'Est' },
  { abbr: 'CHI', name: 'Bulls', city: 'Chicago', conference: 'Est' },
  { abbr: 'CLE', name: 'Cavaliers', city: 'Cleveland', conference: 'Est' },
  { abbr: 'DET', name: 'Pistons', city: 'Détroit', conference: 'Est' },
  { abbr: 'IND', name: 'Pacers', city: 'Indiana', conference: 'Est' },
  { abbr: 'MIA', name: 'Heat', city: 'Miami', conference: 'Est' },
  { abbr: 'MIL', name: 'Bucks', city: 'Milwaukee', conference: 'Est' },
  { abbr: 'NYK', name: 'Knicks', city: 'New York', conference: 'Est' },
  { abbr: 'ORL', name: 'Magic', city: 'Orlando', conference: 'Est' },
  { abbr: 'PHI', name: '76ers', city: 'Philadelphie', conference: 'Est' },
  { abbr: 'TOR', name: 'Raptors', city: 'Toronto', conference: 'Est' },
  { abbr: 'WAS', name: 'Wizards', city: 'Washington', conference: 'Est' },
  { abbr: 'DAL', name: 'Mavericks', city: 'Dallas', conference: 'Ouest' },
  { abbr: 'DEN', name: 'Nuggets', city: 'Denver', conference: 'Ouest' },
  { abbr: 'GSW', name: 'Warriors', city: 'Golden State', conference: 'Ouest' },
  { abbr: 'HOU', name: 'Rockets', city: 'Houston', conference: 'Ouest' },
  { abbr: 'LAC', name: 'Clippers', city: 'Los Angeles', conference: 'Ouest' },
  { abbr: 'LAL', name: 'Lakers', city: 'Los Angeles', conference: 'Ouest' },
  { abbr: 'MEM', name: 'Grizzlies', city: 'Memphis', conference: 'Ouest' },
  { abbr: 'MIN', name: 'Timberwolves', city: 'Minnesota', conference: 'Ouest' },
  { abbr: 'NOP', name: 'Pelicans', city: 'La Nouvelle-Orléans', conference: 'Ouest' },
  { abbr: 'OKC', name: 'Thunder', city: 'Oklahoma City', conference: 'Ouest' },
  { abbr: 'PHX', name: 'Suns', city: 'Phoenix', conference: 'Ouest' },
  { abbr: 'POR', name: 'Trail Blazers', city: 'Portland', conference: 'Ouest' },
  { abbr: 'SAC', name: 'Kings', city: 'Sacramento', conference: 'Ouest' },
  { abbr: 'SAS', name: 'Spurs', city: 'San Antonio', conference: 'Ouest' },
  { abbr: 'UTA', name: 'Jazz', city: 'Utah', conference: 'Ouest' },
];

export const PLAYERS: SeedPlayer[] = [
  // Atlanta Hawks
  { name: 'Trae Young', team: 'ATL', pos: 'MJ', rating: 89 },
  { name: 'Dyson Daniels', team: 'ATL', pos: 'AR', rating: 80 },
  { name: 'Bogdan Bogdanovic', team: 'ATL', pos: 'AR', rating: 77 },
  { name: 'Zaccharie Risacher', team: 'ATL', pos: 'AI', rating: 75 },
  { name: 'De\'Andre Hunter', team: 'ATL', pos: 'AI', rating: 78 },
  { name: 'Jalen Johnson', team: 'ATL', pos: 'AF', rating: 83 },
  { name: 'Onyeka Okongwu', team: 'ATL', pos: 'PI', rating: 78 },
  { name: 'Clint Capela', team: 'ATL', pos: 'PI', rating: 76 },
  // Boston Celtics
  { name: 'Jayson Tatum', team: 'BOS', pos: 'AI', rating: 95 },
  { name: 'Jaylen Brown', team: 'BOS', pos: 'AR', rating: 90 },
  { name: 'Derrick White', team: 'BOS', pos: 'MJ', rating: 83 },
  { name: 'Jrue Holiday', team: 'BOS', pos: 'MJ', rating: 81 },
  { name: 'Kristaps Porzingis', team: 'BOS', pos: 'PI', rating: 84 },
  { name: 'Al Horford', team: 'BOS', pos: 'PI', rating: 76 },
  { name: 'Sam Hauser', team: 'BOS', pos: 'AI', rating: 72 },
  { name: 'Payton Pritchard', team: 'BOS', pos: 'MJ', rating: 77 },
  // Brooklyn Nets
  { name: 'Cam Thomas', team: 'BKN', pos: 'AR', rating: 80 },
  { name: 'Dennis Schroder', team: 'BKN', pos: 'MJ', rating: 76 },
  { name: 'Cameron Johnson', team: 'BKN', pos: 'AI', rating: 79 },
  { name: 'Dorian Finney-Smith', team: 'BKN', pos: 'AF', rating: 73 },
  { name: 'Nic Claxton', team: 'BKN', pos: 'PI', rating: 78 },
  { name: 'Ben Simmons', team: 'BKN', pos: 'MJ', rating: 72 },
  { name: 'Ziaire Williams', team: 'BKN', pos: 'AI', rating: 70 },
  { name: 'Day\'Ron Sharpe', team: 'BKN', pos: 'PI', rating: 71 },
  // Charlotte Hornets
  { name: 'LaMelo Ball', team: 'CHA', pos: 'MJ', rating: 86 },
  { name: 'Brandon Miller', team: 'CHA', pos: 'AI', rating: 82 },
  { name: 'Miles Bridges', team: 'CHA', pos: 'AF', rating: 79 },
  { name: 'Mark Williams', team: 'CHA', pos: 'PI', rating: 77 },
  { name: 'Tre Mann', team: 'CHA', pos: 'MJ', rating: 72 },
  { name: 'Josh Green', team: 'CHA', pos: 'AR', rating: 71 },
  { name: 'Grant Williams', team: 'CHA', pos: 'AF', rating: 72 },
  { name: 'Nick Richards', team: 'CHA', pos: 'PI', rating: 72 },
  // Chicago Bulls
  { name: 'Zach LaVine', team: 'CHI', pos: 'AR', rating: 84 },
  { name: 'Coby White', team: 'CHI', pos: 'MJ', rating: 80 },
  { name: 'Josh Giddey', team: 'CHI', pos: 'MJ', rating: 79 },
  { name: 'Nikola Vucevic', team: 'CHI', pos: 'PI', rating: 81 },
  { name: 'Patrick Williams', team: 'CHI', pos: 'AF', rating: 74 },
  { name: 'Ayo Dosunmu', team: 'CHI', pos: 'AR', rating: 75 },
  { name: 'Matas Buzelis', team: 'CHI', pos: 'AF', rating: 73 },
  { name: 'Jalen Smith', team: 'CHI', pos: 'PI', rating: 71 },
  // Cleveland Cavaliers
  { name: 'Donovan Mitchell', team: 'CLE', pos: 'AR', rating: 91 },
  { name: 'Darius Garland', team: 'CLE', pos: 'MJ', rating: 85 },
  { name: 'Evan Mobley', team: 'CLE', pos: 'AF', rating: 87 },
  { name: 'Jarrett Allen', team: 'CLE', pos: 'PI', rating: 82 },
  { name: 'Max Strus', team: 'CLE', pos: 'AI', rating: 74 },
  { name: 'Isaac Okoro', team: 'CLE', pos: 'AI', rating: 72 },
  { name: 'Ty Jerome', team: 'CLE', pos: 'MJ', rating: 74 },
  { name: 'Caris LeVert', team: 'CLE', pos: 'AR', rating: 75 },
  // Detroit Pistons
  { name: 'Cade Cunningham', team: 'DET', pos: 'MJ', rating: 89 },
  { name: 'Jaden Ivey', team: 'DET', pos: 'AR', rating: 78 },
  { name: 'Malik Beasley', team: 'DET', pos: 'AR', rating: 75 },
  { name: 'Tobias Harris', team: 'DET', pos: 'AF', rating: 77 },
  { name: 'Ausar Thompson', team: 'DET', pos: 'AI', rating: 76 },
  { name: 'Jalen Duren', team: 'DET', pos: 'PI', rating: 79 },
  { name: 'Isaiah Stewart', team: 'DET', pos: 'PI', rating: 73 },
  { name: 'Tim Hardaway Jr.', team: 'DET', pos: 'AR', rating: 73 },
  // Indiana Pacers
  { name: 'Tyrese Haliburton', team: 'IND', pos: 'MJ', rating: 90 },
  { name: 'Pascal Siakam', team: 'IND', pos: 'AF', rating: 86 },
  { name: 'Myles Turner', team: 'IND', pos: 'PI', rating: 80 },
  { name: 'Bennedict Mathurin', team: 'IND', pos: 'AR', rating: 78 },
  { name: 'Andrew Nembhard', team: 'IND', pos: 'MJ', rating: 76 },
  { name: 'Aaron Nesmith', team: 'IND', pos: 'AI', rating: 75 },
  { name: 'Obi Toppin', team: 'IND', pos: 'AF', rating: 74 },
  { name: 'T.J. McConnell', team: 'IND', pos: 'MJ', rating: 73 },
  // Miami Heat
  { name: 'Jimmy Butler', team: 'MIA', pos: 'AI', rating: 88 },
  { name: 'Bam Adebayo', team: 'MIA', pos: 'PI', rating: 87 },
  { name: 'Tyler Herro', team: 'MIA', pos: 'AR', rating: 84 },
  { name: 'Terry Rozier', team: 'MIA', pos: 'MJ', rating: 76 },
  { name: 'Jaime Jaquez Jr.', team: 'MIA', pos: 'AI', rating: 74 },
  { name: 'Nikola Jovic', team: 'MIA', pos: 'AF', rating: 73 },
  { name: 'Kel\'el Ware', team: 'MIA', pos: 'PI', rating: 75 },
  { name: 'Duncan Robinson', team: 'MIA', pos: 'AI', rating: 73 },
  // Milwaukee Bucks
  { name: 'Giannis Antetokounmpo', team: 'MIL', pos: 'AF', rating: 97 },
  { name: 'Damian Lillard', team: 'MIL', pos: 'MJ', rating: 90 },
  { name: 'Khris Middleton', team: 'MIL', pos: 'AI', rating: 78 },
  { name: 'Brook Lopez', team: 'MIL', pos: 'PI', rating: 79 },
  { name: 'Bobby Portis', team: 'MIL', pos: 'AF', rating: 76 },
  { name: 'Gary Trent Jr.', team: 'MIL', pos: 'AR', rating: 74 },
  { name: 'Taurean Prince', team: 'MIL', pos: 'AI', rating: 71 },
  { name: 'AJ Green', team: 'MIL', pos: 'AR', rating: 70 },
  // New York Knicks
  { name: 'Jalen Brunson', team: 'NYK', pos: 'MJ', rating: 92 },
  { name: 'Karl-Anthony Towns', team: 'NYK', pos: 'PI', rating: 90 },
  { name: 'Mikal Bridges', team: 'NYK', pos: 'AI', rating: 82 },
  { name: 'OG Anunoby', team: 'NYK', pos: 'AF', rating: 81 },
  { name: 'Josh Hart', team: 'NYK', pos: 'AR', rating: 80 },
  { name: 'Mitchell Robinson', team: 'NYK', pos: 'PI', rating: 74 },
  { name: 'Miles McBride', team: 'NYK', pos: 'MJ', rating: 73 },
  { name: 'Precious Achiuwa', team: 'NYK', pos: 'AF', rating: 71 },
  // Orlando Magic
  { name: 'Paolo Banchero', team: 'ORL', pos: 'AF', rating: 89 },
  { name: 'Franz Wagner', team: 'ORL', pos: 'AI', rating: 87 },
  { name: 'Jalen Suggs', team: 'ORL', pos: 'MJ', rating: 79 },
  { name: 'Wendell Carter Jr.', team: 'ORL', pos: 'PI', rating: 76 },
  { name: 'Kentavious Caldwell-Pope', team: 'ORL', pos: 'AR', rating: 74 },
  { name: 'Anthony Black', team: 'ORL', pos: 'MJ', rating: 73 },
  { name: 'Goga Bitadze', team: 'ORL', pos: 'PI', rating: 72 },
  { name: 'Jonathan Isaac', team: 'ORL', pos: 'AF', rating: 73 },
  // Philadelphia 76ers
  { name: 'Joel Embiid', team: 'PHI', pos: 'PI', rating: 94 },
  { name: 'Tyrese Maxey', team: 'PHI', pos: 'MJ', rating: 89 },
  { name: 'Paul George', team: 'PHI', pos: 'AI', rating: 86 },
  { name: 'Kelly Oubre Jr.', team: 'PHI', pos: 'AI', rating: 76 },
  { name: 'Jared McCain', team: 'PHI', pos: 'AR', rating: 77 },
  { name: 'Caleb Martin', team: 'PHI', pos: 'AF', rating: 73 },
  { name: 'Andre Drummond', team: 'PHI', pos: 'PI', rating: 73 },
  { name: 'Kyle Lowry', team: 'PHI', pos: 'MJ', rating: 70 },
  // Toronto Raptors
  { name: 'Scottie Barnes', team: 'TOR', pos: 'AF', rating: 85 },
  { name: 'RJ Barrett', team: 'TOR', pos: 'AI', rating: 81 },
  { name: 'Immanuel Quickley', team: 'TOR', pos: 'MJ', rating: 79 },
  { name: 'Gradey Dick', team: 'TOR', pos: 'AR', rating: 75 },
  { name: 'Jakob Poeltl', team: 'TOR', pos: 'PI', rating: 78 },
  { name: 'Ochai Agbaji', team: 'TOR', pos: 'AR', rating: 71 },
  { name: 'Chris Boucher', team: 'TOR', pos: 'AF', rating: 71 },
  { name: 'Jamal Shead', team: 'TOR', pos: 'MJ', rating: 70 },
  // Washington Wizards
  { name: 'Jordan Poole', team: 'WAS', pos: 'AR', rating: 78 },
  { name: 'Kyle Kuzma', team: 'WAS', pos: 'AF', rating: 77 },
  { name: 'Bilal Coulibaly', team: 'WAS', pos: 'AI', rating: 75 },
  { name: 'Alex Sarr', team: 'WAS', pos: 'PI', rating: 76 },
  { name: 'Jonas Valanciunas', team: 'WAS', pos: 'PI', rating: 75 },
  { name: 'Bub Carrington', team: 'WAS', pos: 'MJ', rating: 72 },
  { name: 'Corey Kispert', team: 'WAS', pos: 'AI', rating: 72 },
  { name: 'Malcolm Brogdon', team: 'WAS', pos: 'MJ', rating: 74 },
  // Dallas Mavericks
  { name: 'Luka Doncic', team: 'DAL', pos: 'MJ', rating: 97 },
  { name: 'Kyrie Irving', team: 'DAL', pos: 'AR', rating: 89 },
  { name: 'Klay Thompson', team: 'DAL', pos: 'AR', rating: 78 },
  { name: 'P.J. Washington', team: 'DAL', pos: 'AF', rating: 77 },
  { name: 'Dereck Lively II', team: 'DAL', pos: 'PI', rating: 78 },
  { name: 'Daniel Gafford', team: 'DAL', pos: 'PI', rating: 76 },
  { name: 'Naji Marshall', team: 'DAL', pos: 'AI', rating: 73 },
  { name: 'Spencer Dinwiddie', team: 'DAL', pos: 'MJ', rating: 73 },
  // Denver Nuggets
  { name: 'Nikola Jokic', team: 'DEN', pos: 'PI', rating: 99 },
  { name: 'Jamal Murray', team: 'DEN', pos: 'MJ', rating: 86 },
  { name: 'Michael Porter Jr.', team: 'DEN', pos: 'AI', rating: 81 },
  { name: 'Aaron Gordon', team: 'DEN', pos: 'AF', rating: 80 },
  { name: 'Christian Braun', team: 'DEN', pos: 'AR', rating: 76 },
  { name: 'Russell Westbrook', team: 'DEN', pos: 'MJ', rating: 75 },
  { name: 'Peyton Watson', team: 'DEN', pos: 'AI', rating: 72 },
  { name: 'DeAndre Jordan', team: 'DEN', pos: 'PI', rating: 68 },
  // Golden State Warriors
  { name: 'Stephen Curry', team: 'GSW', pos: 'MJ', rating: 94 },
  { name: 'Draymond Green', team: 'GSW', pos: 'AF', rating: 79 },
  { name: 'Andrew Wiggins', team: 'GSW', pos: 'AI', rating: 78 },
  { name: 'Buddy Hield', team: 'GSW', pos: 'AR', rating: 76 },
  { name: 'Jonathan Kuminga', team: 'GSW', pos: 'AF', rating: 79 },
  { name: 'Brandin Podziemski', team: 'GSW', pos: 'AR', rating: 74 },
  { name: 'Trayce Jackson-Davis', team: 'GSW', pos: 'PI', rating: 74 },
  { name: 'Kevon Looney', team: 'GSW', pos: 'PI', rating: 70 },
  // Houston Rockets
  { name: 'Alperen Sengun', team: 'HOU', pos: 'PI', rating: 87 },
  { name: 'Jalen Green', team: 'HOU', pos: 'AR', rating: 82 },
  { name: 'Fred VanVleet', team: 'HOU', pos: 'MJ', rating: 79 },
  { name: 'Amen Thompson', team: 'HOU', pos: 'AI', rating: 80 },
  { name: 'Jabari Smith Jr.', team: 'HOU', pos: 'AF', rating: 77 },
  { name: 'Dillon Brooks', team: 'HOU', pos: 'AI', rating: 75 },
  { name: 'Tari Eason', team: 'HOU', pos: 'AF', rating: 75 },
  { name: 'Steven Adams', team: 'HOU', pos: 'PI', rating: 72 },
  // Los Angeles Clippers
  { name: 'James Harden', team: 'LAC', pos: 'MJ', rating: 87 },
  { name: 'Kawhi Leonard', team: 'LAC', pos: 'AI', rating: 85 },
  { name: 'Norman Powell', team: 'LAC', pos: 'AR', rating: 81 },
  { name: 'Ivica Zubac', team: 'LAC', pos: 'PI', rating: 80 },
  { name: 'Derrick Jones Jr.', team: 'LAC', pos: 'AI', rating: 73 },
  { name: 'Terance Mann', team: 'LAC', pos: 'AR', rating: 72 },
  { name: 'Nicolas Batum', team: 'LAC', pos: 'AF', rating: 71 },
  { name: 'Kris Dunn', team: 'LAC', pos: 'MJ', rating: 71 },
  // Los Angeles Lakers
  { name: 'LeBron James', team: 'LAL', pos: 'AI', rating: 94 },
  { name: 'Anthony Davis', team: 'LAL', pos: 'PI', rating: 93 },
  { name: 'Austin Reaves', team: 'LAL', pos: 'AR', rating: 81 },
  { name: 'D\'Angelo Russell', team: 'LAL', pos: 'MJ', rating: 77 },
  { name: 'Rui Hachimura', team: 'LAL', pos: 'AF', rating: 76 },
  { name: 'Dalton Knecht', team: 'LAL', pos: 'AR', rating: 74 },
  { name: 'Jaxson Hayes', team: 'LAL', pos: 'PI', rating: 71 },
  { name: 'Gabe Vincent', team: 'LAL', pos: 'MJ', rating: 70 },
  // Memphis Grizzlies
  { name: 'Ja Morant', team: 'MEM', pos: 'MJ', rating: 89 },
  { name: 'Jaren Jackson Jr.', team: 'MEM', pos: 'AF', rating: 86 },
  { name: 'Desmond Bane', team: 'MEM', pos: 'AR', rating: 83 },
  { name: 'Zach Edey', team: 'MEM', pos: 'PI', rating: 76 },
  { name: 'Marcus Smart', team: 'MEM', pos: 'MJ', rating: 74 },
  { name: 'Jaylen Wells', team: 'MEM', pos: 'AI', rating: 73 },
  { name: 'Santi Aldama', team: 'MEM', pos: 'AF', rating: 74 },
  { name: 'Brandon Clarke', team: 'MEM', pos: 'PI', rating: 72 },
  // Minnesota Timberwolves
  { name: 'Anthony Edwards', team: 'MIN', pos: 'AR', rating: 93 },
  { name: 'Rudy Gobert', team: 'MIN', pos: 'PI', rating: 84 },
  { name: 'Julius Randle', team: 'MIN', pos: 'AF', rating: 82 },
  { name: 'Mike Conley', team: 'MIN', pos: 'MJ', rating: 74 },
  { name: 'Jaden McDaniels', team: 'MIN', pos: 'AI', rating: 77 },
  { name: 'Naz Reid', team: 'MIN', pos: 'PI', rating: 78 },
  { name: 'Donte DiVincenzo', team: 'MIN', pos: 'AR', rating: 75 },
  { name: 'Rob Dillingham', team: 'MIN', pos: 'MJ', rating: 72 },
  // New Orleans Pelicans
  { name: 'Zion Williamson', team: 'NOP', pos: 'AF', rating: 88 },
  { name: 'Brandon Ingram', team: 'NOP', pos: 'AI', rating: 84 },
  { name: 'CJ McCollum', team: 'NOP', pos: 'MJ', rating: 80 },
  { name: 'Trey Murphy III', team: 'NOP', pos: 'AI', rating: 79 },
  { name: 'Herbert Jones', team: 'NOP', pos: 'AF', rating: 75 },
  { name: 'Dejounte Murray', team: 'NOP', pos: 'AR', rating: 80 },
  { name: 'Yves Missi', team: 'NOP', pos: 'PI', rating: 74 },
  { name: 'Jose Alvarado', team: 'NOP', pos: 'MJ', rating: 71 },
  // Oklahoma City Thunder
  { name: 'Shai Gilgeous-Alexander', team: 'OKC', pos: 'MJ', rating: 96 },
  { name: 'Jalen Williams', team: 'OKC', pos: 'AI', rating: 86 },
  { name: 'Chet Holmgren', team: 'OKC', pos: 'PI', rating: 85 },
  { name: 'Luguentz Dort', team: 'OKC', pos: 'AR', rating: 75 },
  { name: 'Isaiah Hartenstein', team: 'OKC', pos: 'PI', rating: 78 },
  { name: 'Alex Caruso', team: 'OKC', pos: 'AR', rating: 74 },
  { name: 'Cason Wallace', team: 'OKC', pos: 'MJ', rating: 74 },
  { name: 'Kenrich Williams', team: 'OKC', pos: 'AF', rating: 70 },
  // Phoenix Suns
  { name: 'Kevin Durant', team: 'PHX', pos: 'AF', rating: 92 },
  { name: 'Devin Booker', team: 'PHX', pos: 'AR', rating: 90 },
  { name: 'Bradley Beal', team: 'PHX', pos: 'AR', rating: 80 },
  { name: 'Jusuf Nurkic', team: 'PHX', pos: 'PI', rating: 75 },
  { name: 'Grayson Allen', team: 'PHX', pos: 'AI', rating: 74 },
  { name: 'Tyus Jones', team: 'PHX', pos: 'MJ', rating: 75 },
  { name: 'Royce O\'Neale', team: 'PHX', pos: 'AF', rating: 72 },
  { name: 'Mason Plumlee', team: 'PHX', pos: 'PI', rating: 69 },
  // Portland Trail Blazers
  { name: 'Anfernee Simons', team: 'POR', pos: 'AR', rating: 81 },
  { name: 'Scoot Henderson', team: 'POR', pos: 'MJ', rating: 76 },
  { name: 'Deni Avdija', team: 'POR', pos: 'AI', rating: 79 },
  { name: 'Jerami Grant', team: 'POR', pos: 'AF', rating: 78 },
  { name: 'Deandre Ayton', team: 'POR', pos: 'PI', rating: 79 },
  { name: 'Shaedon Sharpe', team: 'POR', pos: 'AR', rating: 77 },
  { name: 'Toumani Camara', team: 'POR', pos: 'AF', rating: 74 },
  { name: 'Donovan Clingan', team: 'POR', pos: 'PI', rating: 74 },
  // Sacramento Kings
  { name: 'De\'Aaron Fox', team: 'SAC', pos: 'MJ', rating: 89 },
  { name: 'Domantas Sabonis', team: 'SAC', pos: 'PI', rating: 89 },
  { name: 'DeMar DeRozan', team: 'SAC', pos: 'AI', rating: 84 },
  { name: 'Malik Monk', team: 'SAC', pos: 'AR', rating: 78 },
  { name: 'Keegan Murray', team: 'SAC', pos: 'AF', rating: 78 },
  { name: 'Kevin Huerter', team: 'SAC', pos: 'AR', rating: 72 },
  { name: 'Trey Lyles', team: 'SAC', pos: 'AF', rating: 71 },
  { name: 'Keon Ellis', team: 'SAC', pos: 'AR', rating: 71 },
  // San Antonio Spurs
  { name: 'Victor Wembanyama', team: 'SAS', pos: 'PI', rating: 93 },
  { name: 'Stephon Castle', team: 'SAS', pos: 'MJ', rating: 78 },
  { name: 'Devin Vassell', team: 'SAS', pos: 'AR', rating: 79 },
  { name: 'Chris Paul', team: 'SAS', pos: 'MJ', rating: 76 },
  { name: 'Harrison Barnes', team: 'SAS', pos: 'AF', rating: 74 },
  { name: 'Keldon Johnson', team: 'SAS', pos: 'AI', rating: 75 },
  { name: 'Jeremy Sochan', team: 'SAS', pos: 'AF', rating: 75 },
  { name: 'Zach Collins', team: 'SAS', pos: 'PI', rating: 72 },
  // Utah Jazz
  { name: 'Lauri Markkanen', team: 'UTA', pos: 'AF', rating: 84 },
  { name: 'Collin Sexton', team: 'UTA', pos: 'MJ', rating: 78 },
  { name: 'Jordan Clarkson', team: 'UTA', pos: 'AR', rating: 75 },
  { name: 'John Collins', team: 'UTA', pos: 'AF', rating: 76 },
  { name: 'Walker Kessler', team: 'UTA', pos: 'PI', rating: 78 },
  { name: 'Keyonte George', team: 'UTA', pos: 'MJ', rating: 75 },
  { name: 'Taylor Hendricks', team: 'UTA', pos: 'AF', rating: 71 },
  { name: 'Kyle Filipowski', team: 'UTA', pos: 'PI', rating: 71 },
];

// Cote au mercato (en millions) dérivée du niveau du joueur.
export function ratingToCote(rating: number): number {
  return Math.max(1, Math.round(Math.pow(Math.max(0, rating - 62), 1.45) / 4));
}
